### ISSUE TITLE
sleep a little too short

### ISSUE THREAD

**Issue by ripoul** [Zenika/github-insights#4]
I think [this](https://github.com/Zenika/github-insights/blob/4c55c96fa3e474fec0e28d542bd7526ecd2868db/index.js#L139) sleep is not enougth : I've got some strange random error while fetching the repositories of the organization.

By increasing the break time the error didn't show up again.

**Comment by frinyvonnick** [comment]
How much did you increased it ?

**Comment by ripoul** [comment]
*2 just to be sure...

**Comment by frinyvonnick** [comment]
I don't have any problem but you could let the possibility to overwrite this time ? Maybe with cli option or env variable ?

**Comment by ripoul** [comment]
This problem appears after several utilisation (50 with the same GitHub
token) . Increase the break seams to solve the problem for now. The cli or
env variable is a good idee but isn't it to specific to be set here?

Le lun. 1 avr. 2019 à 21:12, FRIN Yvonnick <notifications@github.com> a
écrit :

**Comment by ripoul** [comment]
```
[GraphQL error]: Message: Something went wrong while executing your query. Please include `86B2:2609:350B9C:698E28:5CA4935E` when reporting this issue., Location: undefined, Path: undefined
{ Error: GraphQL error: Something went wrong while executing your query. Please include `86B2:2609:350B9C:698E28:5CA4935E` when reporting this issue.
    at new ApolloError (/home/ripoul/Documents/epsi/cloud/project/github-insight/node_modules/apollo-client/bundle.umd.js:59:32)
    at QueryManager.<anonymous> (/home/ripoul/Documents/epsi/cloud/project/github-insight/node_modules/apollo-client/bundle.umd.js:1183:49)
    at step (/home/ripoul/Documents/epsi/cloud/project/github-insight/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/ripoul/Documents/epsi/cloud/project/github-insight/node_modules/tslib/tslib.js:114:57)
    at /home/ripoul/Documents/epsi/cloud/project/github-insight/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/ripoul/Documents/epsi/cloud/project/github-insight/node_modules/tslib/tslib.js:103:16)
    at /home/ripoul/Documents/epsi/cloud/project/github-insight/node_modules/apollo-client/bundle.umd.js:1146:87
    at /home/ripoul/Documents/epsi/cloud/project/github-insight/node_modules/apollo-client/bundle.umd.js:1626:21
    at Array.forEach (<anonymous>)
  graphQLErrors:
   [ { message:
        'Something went wrong while executing your query. Please include `86B2:2609:350B9C:698E28:5CA4935E` when reporting this issue.' } ],
  networkError: null,
  message:
   'GraphQL error: Something went wrong while executing your query. Please include `86B2:2609:350B9C:698E28:5CA4935E` when reporting this issue.',
  extraInfo: undefined }
(node:5815) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at /home/ripoul/Documents/epsi/cloud/project/github-insight/get.js:243:38
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:5815) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5815) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Is that possible that appolo not hundle the rate limit ?

**Comment by frinyvonnick** [comment]
There is a `Cannot read property 'data' of undefined` can you share the code of `get.js` in a gist ?

**Comment by ripoul** [comment]
it's the next error created by the first one. You can find the code [here](https://github.com/ripoul/github-insights/blob/dev/get.js).
